version: '3.4'
services:
  populationanalytics.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
  flyway:
    entrypoint:
      - /bin/sh
      - -c
      - |
        /flyway/flyway -url=jdbc:postgresql://postgresql/PopulationAnalyticsDb -locations=filesystem:/flyway/sql/PopulationAnalyticsDb -user=postgres -password=password -connectRetries=200 migrate
    volumes:
      - ./data/postgresql/migrations/PopulationAnalyticsDb:/flyway/sql
