version: '3.4'
services:
  populationanalytics.api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__StudentManagementDb: "Server=sqlserver;Database=StudentManagementDb;User Id=sa;Password=@someThingComplicated1234;"
    ports:
      - "5000:80"
  flyway:
    entrypoint:
      - /bin/sh
      - -c
      - |
        /flyway/flyway -url=jdbc:postgresql://postgresql/PopulationAnalyticsDb -locations=filesystem:/flyway/sql/PopulationAnalyticsDb -user=postgres -password=password -connectRetries=200 migrate \
        && /flyway/flyway -url=jdbc:postgresql://postgresql/PopulationAnalyticsDb2 -locations=filesystem:/flyway/sql/PopulationAnalyticsDb2 -user=postgres -password=password -connectRetries=200 migrate
    volumes:
      - ./data/postgresql/migrations:/flyway/sql
