version: '3.4'

services:
  populationanalytics.api:
    build:
      context: .
      dockerfile: src/PopulationAnalytics.Api/Dockerfile
    depends_on:
      - postgresql
    ports:
        - "5000:80"
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PopulationAnalyticsDb
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  flyway:
    image: flyway/flyway
    depends_on:
      - postgresql


